#!/bin/sh
# Author: Jamie Alexandre
# Project: KA Lite
# Purpose:
#   Startup script for KA Lite server service.
#   Goes in: /etc/init.d/service/S90kalite
# History:
# 2014/10/09 - First version
# 2015/11/08 - Updated to work with KA Lite v0.16

case "$1" in

        start)
                # Block direct access to the Sandisk portal page on port 83
                iptables -A INPUT -i wlan0 -p tcp --dport 83 -j DROP
                iptables -A INPUT -i wlan1 -p tcp --dport 83 -j DROP
                
                # Start up the helper scripts
                python /root/scripts/resolve_all_dns_to_host_ip.py &
                python /root/scripts/redirect_port_80_to_kalite.py &
                python /root/scripts/proxy_sandisk_portal.py &
                
                echo "Starting ka-lite..."
                KALITE_HOME=/root/.kalite PYTHONPATH=/mnt/storage/ka-lite/dist-packages python /mnt/storage/ka-lite/kalitectl.py start
                wget http://127.0.0.1:8008/ -O /dev/null
                ;;
             
        stop)                                  
                echo "Shutting down ka-lite..."                                                            
                KALITE_HOME=/root/.kalite PYTHONPATH=/mnt/storage/ka-lite/dist-packages python /mnt/storage/ka-lite/kalitectl.py stop
                pkill -f resolve_all_dns_to_host_ip.py
                pkill -f redirect_port_80_to_kalite.py
                ;;
                
        restart)                                                                                              
                /etc/init.d/service/S90kalite stop
                /etc/init.d/service/S90kalite start
                ;;
          
        *)                                           
                echo "Usage: $0 (start|stop|restart)"
                exit 1
                ;;
esac
      
exit 0
