#!/bin/sh
# Author: Jamie Alexandre
# Project: KA Lite
# Purpose:
#   For KA Lite server service.
#   Goes in: /etc/rc.d/init.d/service/S90kalite
# History:
# 2014/10/09 - First version

case "$1" in

        start)
                echo "Starting ka-lite..."
                su admin -c "/mnt/storage/ka-lite/start.sh"
                ;;

        stop)
                echo "Shutting down ka-lite..."
                "/mnt/storage/ka-lite/kalite/stop.sh"
                ;;

        restart)
                $0 stop
                sleep 1
                $0 start
                ;;

        *)
                echo "Usage: $0 (start|stop|restart)"
                exit 1
                ;;
esac

exit 0